/*
  + Here, we define system code which is a part of this APP and a part of
  basing on code messages from the SERVER.
*/

const UNKNOWN = "UNDEFINE";

const MAINTENANCE = "MAINTENANCE";
const LOG_OUT = "LOG_OUT";
const FORCE_UPDATE = "FORCE_UPDATE";
const ALERT_UPDATE = "ALERT_UPDATE";

const ACCESS_DENY = "ACCESS_DENY";
const UPDATE_FAIL = "UPDATE_FAIL";
const UNAUTHORIZED = "UNAUTHORIZED";
const FORBIDDEN = "FORBIDDEN";

const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
const INVALID_PHONE_LENGTH = "INVALID_PHONE_LENGTH";
const PHONE_IS_NOT_IN_SYSTEM = "PHONE_NOT_EXISTED";
const DONT_HAVE_PERMISSION = "DONT_HAVE_PERMISSION";
const CAMERA_AI_UPDATE_IMAGE_FAIL = "CAMERA_AI_UPDATE_IMAGE_FAIL ";
const LOGIN_WITH_OTP = "LOGIN_WITH_OTP";
const LOGIN_WITH_PASSWORD = "LOGIN_WITH_PASSWORD";
const LOGIN_WITH_APPLE = "LOGIN_WITH_APPLE";
const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
const SELECT_COMPANY = "SELECT_COMPANY";

const CREATE_USER_FAILED_DUE_TO_DUPLICATED_UNIQUE_DATA =
    "CREATE_USER_FAILED_DUE_TO_DUPLICATED_UNIQUE_DATA";
const BAD_REQUEST = "BAD_REQUEST";

const AUTH_WRONG_USER_NAME_OR_PASSWORD = "AUTH_WRONG_USER_NAME_OR_PASSWORD";
const ACCOUNT_PHONE_EXISTED = "ACCOUNT_PHONE_EXISTED";
const ACCOUNT_EMAIL_EXISTED = "ACCOUNT_EMAIL_EXISTED";
const ACCOUNT_IDENTITY_CARD_EXISTED = "ACCOUNT_IDENTITY_CARD_EXISTED";
const ACCOUNT_DEVICE_CODE_EXISTED = "ACCOUNT_DEVICE_CODE_EXISTED";
const PRODUCT_NAME_EXISTED = "PRODUCT_NAME_EXISTED";
const PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND";
const PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK";
const CANNOT_DECRYPT_TOKEN = "CAN'T_DECRYPT_TOKEN";
const SHIPPING_NOT_FOUND = "SHIPPING_NOT_FOUND";
const STAFF_NOT_BELONG_TO_WAREHOUSE = "STAFF_NOT_BELONG_TO_WAREHOUSE";
const SHIPPING_CAN_NOT_FINISH = "SHIPPING_CAN_NOT_FINISH";
const ORDER_UPDATE_TO_PENDING_STATUS = "ORDER_UPDATE_TO_PENDING_STATUS";
const CAMPAIGN_EXISTED = "CAMPAIGN_EXISTED";
const CAMPAIGN_NOT_FOUND = "CAMPAIGN_NOT_FOUND";
const CAMPAIGN_TYPE_CAMPAIGN_NOT_FOUND = "CAMPAIGN_TYPE_CAMPAIGN_NOT_FOUND";
const CAMPAIGN_TYPE_CYCLE_NOT_FOUND = "CAMPAIGN_TYPE_CYCLE_NOT_FOUND";
const CAMPAIGN_TYPE_LEVEL_NOT_FOUND = "CAMPAIGN_TYPE_LEVEL_NOT_FOUND";
const CAMPAIGN_TYPE_GIFT_NOT_FOUND = "CAMPAIGN_TYPE_GIFT_NOT_FOUND";
const WAREHOUSE_NOT_FOUND = "WAREHOUSE_NOT_FOUND";
const SHIPPING_NOT_ALLOW = "SHIPPING_NOT_ALLOW";
const SHIPPING_TOKEN_EXPIRED = "SHIPPING_TOKEN_EXPIRED";
const ORDER_IMAGES_NOT_FOUND = "ORDER_IMAGES_NOT_FOUND";
const ORDER_CANT_UPDATE = "ORDER_CANT_UPDATE";
const ORDER_MONEY_ISSUE = "ORDER_MONEY_ISSUE";
const ORDER_NOT_FOUND = "ORDER_NOT_FOUND";
const CATEGORY_EXISTED = "CATEGORY_EXISTED";
const CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
const DEVICE_NOT_MATCH = "DEVICE_NOT_MATCH";
const DEVICE_NEED_2_FIX = "DEVICE_NEED_2_FIX";
const DEVICE_EMPTY_ENERGY = "DEVICE_EMPTY_ENERGY";
const DEVICE_NOT_ALLOW = "DEVICE_NOT_ALLOW";
const DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND";
const DEVICE_CODE_EXISTED = "DEVICE_CODE_EXISTED";
const STAFF_IDENTITY_CARD_EXISTED = "STAFF_IDENTITY_CARD_EXISTED";
const STAFF_EMAIL_EXISTED = "STAFF_EMAIL_EXISTED";
const STAFF_PHONE_EXISTED = "STAFF_PHONE_EXISTED";
const STAFF_NOT_FOUND = "STAFF_NOT_FOUND";
const ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
const ACCOUNT_PHONE_NOT_FOUND = "ACCOUNT_PHONE_NOT_FOUND";
const ACCOUNT_STATUS_BLACK_LIST = "ACCOUNT_STATUS_BLACK_LIST";
const ACCOUNT_STATUS_IN_ACTIVE = "ACCOUNT_STATUS_IN_ACTIVE";

const FILE_SIZE_UPLOAD = "FILE_SIZE_UPLOAD";
const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";
const FILE_UPLOAD_MALFORMED = "FILE_UPLOAD_MALFORMED";
const FIELD_REQUIRED = "FIELD_REQUIRED";
const INVALID_TOKEN = "INVALID_TOKEN";
const NOT_EVEN_A_TOKEN = "NOT_EVEN_A_TOKEN";
const DECRYPT_JWT_TOKEN = "DECRYPT_JWT_TOKEN";
const COULD_NOT_HANDLE_THIS_TOKEN = "COULD_NOT_HANDLE_THIS_TOKEN";
const TOKEN_EXPIRED = "TOKEN_EXPIRED";
const PERMISSION_DENY = "PERMISSION_DENY";
const JSON_UNMARSHAL = "JSON_UNMARSHAL";
const ISSUE = "ISSUE";

const DEVICE_NOT_SETUP = "DEVICE_NOT_SETUP";
const DEVICE_SETUP = "DEVICE_SETUP";
const DEVICE_NOT_FIX = "DEVICE_NOT_FIX";
const DEVICE_FIXED = "DEVICE_FIXED";
const DEVICE_NOT_REVOKE = "DEVICE_NOT_REVOKE";
const DEVICE_REVOKED = "DEVICE_REVOKED";